#!/bin/bash

VALGRIND=0

while [[ $# -gt 0 ]]; do
  case $1 in
    -v|--valgrind)
      shift # past argument
      VALGRIND=1
      ;;
    *|-h)
      echo "Usage: $(basename $0) [-v|--valgrind]"
      exit 1
      ;;
  esac
done

export LD_LIBRARY_PATH="`pwd`/lib"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

if [[ ${VALGRIND} -ne 0 ]]; then
  valgrind \
  		--track-origins=yes \
  		--leak-check=full \
  		--leak-resolution=high \
  		--error-exitcode=1 \
  		--log-file=test/log/valgrind.log \
  		./test/test_static_lib
      sed -n -e '/SUMMARY:/,$p' ./test/log/valgrind.log
  		echo  -en "\n(Entire log available at: ./test/log/valgrind.log)\n"

else
  ./test/test_lib
fi
